### PR TITLE
Reformatting extra scripts for comparing routine vs optimised filtering

### PR DESCRIPTION
**Pull request by rklocke**
- Reformatted all of extra_scripts so that they can be re-run with arguments
- Added script (create_case_comparison_base.py) to create simple base of all cases and report outcome for adding prioritised variants to for comparisons
- Added script (add_filter_variants_to_excel.py) to add in prioritised variants to the above base Excel
- Added script to generate summaries (generate_summary.py) of how well the tool worked based on the above Excel including each case and the reported, routine and optimised variants (so it's easier to compare when running with different thresholds)
- Changed order of commands in vcf.py so variant will always be flagged as NOT_ASSESSED if gene info isn't available
- Removed ugly scripts which are no longer needed

Documentation of use of extra scripts here: https://cuhbioinformatics.atlassian.net/wiki/spaces/S/pages/2988310574/Testing+of+optimised+filtering+for+severe+early-onset+obesity+testing+on+reported+cases

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3)* status: 11 of 14 files reviewed, 5 unresolved discussions (waiting on @rklocke)

___
*[`extra_scripts/add_filter_variants_to_excel.py` line 80 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_96RlC6mE_hIrphUv:-Nd_96RlC6mE_hIrphUw:b-4hc9my) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/add_filter_variants_to_excel.py#L80)):*
I prefer `.read().splitlines()` instead as it automatically drops the trailing `\n`s:
```
>>> with open('test.txt') as f:
...     lines = f.read().splitlines()
... 
>>> lines[0]
'X222348-GM2216585-1-TWE-M-EGG4_markdup_recalibrated_Haplotyper_annotated_filtered.vcf.gz'
```



_Code quote:_
```Python
        lines = my_file.readlines()
```
___
*[`extra_scripts/add_filter_variants_to_excel.py` line 114 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_D4pl0xRbIbrXgugz:-Nd_D4pm-NQ_er423VxX:bjrqmrf) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/add_filter_variants_to_excel.py#L114)):*
> ```Python
>     grouped_list.append(temp_list)
> 
>     return grouped_list
> ```

if you change to `read().splitlines()` above then you will get empty strings in your `lines_of_text_file` list so `if line == split_value` can just be `if not line:`



_Code quote:_
```Python
    split_value = '\n'
    grouped_list = []
    temp_list = []

    for line in lines_of_txt_file[:-1]:
        if line == split_value:
            grouped_list.append(temp_list)
            temp_list = []
        else:
            temp_list.append(line)
    grouped_list.append(temp_list)

    return grouped_list
```
___
*[`extra_scripts/add_filter_variants_to_excel.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_G0ky0kwan5qb8hA7:-Nd_G0ky0kwan5qb8hA8:b-l4dfyj) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/add_filter_variants_to_excel.py#L142)):*
> ```Python
>         stripped_variants = [
>             variant.replace('\n', '') for variant in stripped_variants
>         ]
> ```

you can just chain your replace calls to one like `variant.replace('\t', ' ').replace('\n', ' ')`.

Do you also need the `str()` in the join below? if not the whole thing can be:
```

```



_Code quote:_
```Python
        stripped_variants = [
            variant.replace('\t', ' ') for variant in variants
        ]
        stripped_variants = [
            variant.replace('\n', '') for variant in stripped_variants
        ]
```
___
*[`extra_scripts/generate_single_vcf_json_and_copy.py` line 210 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_Rfer4-ll3w4a-F4i:-Nd_Rfer4-ll3w4a-F4j:b-zgwoiz) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/generate_single_vcf_json_and_copy.py#L210)):*
> ```Python
>             proj_id = file['project']
>             file_object = dx.DXFile(file_id, project=proj_id)
>             file_object.clone(testing_project_id, folder=f'/{folder_name}')
> ```

feels like a good time to have a go at using concurrent futures to speed this up :) 

this might be helpful as an example: https://binfx.slack.com/archives/G01HV61U4BX/p1667476200344319



_Code quote:_
```Python
    for file in vcf_dict.values():
        if file:
            file_id = file['id']
            proj_id = file['project']
            file_object = dx.DXFile(file_id, project=proj_id)
            file_object.clone(testing_project_id, folder=f'/{folder_name}')
```
___
*[`extra_scripts/generate_summary.py` line 100 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_S79L5ynzkaVSD9Jm:-Nd_S79L5ynzkaVSD9Jn:br1tqzu) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/generate_summary.py#L100)):*
> ```Python
>         "prioritised (false negative)"
>     )
>     print("")
> ```

empty print?



_Code quote:_
```Python
    print("")
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3)* status: 11 of 14 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`extra_scripts/add_filter_variants_to_excel.py` line 80 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_96RlC6mE_hIrphUv:-Nd_pAg01j60wCWUiC77:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/add_filter_variants_to_excel.py#L80)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I prefer `.read().splitlines()` instead as it automatically drops the trailing `\n`s:
```
>>> with open('test.txt') as f:
...     lines = f.read().splitlines()
... 
>>> lines[0]
'X222348-GM2216585-1-TWE-M-EGG4_markdup_recalibrated_Haplotyper_annotated_filtered.vcf.gz'
```
</blockquote></details>

Done.
___
*[`extra_scripts/add_filter_variants_to_excel.py` line 114 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_D4pl0xRbIbrXgugz:-Nd_pK6l6kSEYIegLLsN:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/add_filter_variants_to_excel.py#L114)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you change to `read().splitlines()` above then you will get empty strings in your `lines_of_text_file` list so `if line == split_value` can just be `if not line:`
</blockquote></details>

Done.
___
*[`extra_scripts/add_filter_variants_to_excel.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_G0ky0kwan5qb8hA7:-Nd_pKVX4ga_LuaxuZin:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/add_filter_variants_to_excel.py#L142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you can just chain your replace calls to one like `variant.replace('\t', ' ').replace('\n', ' ')`.

Do you also need the `str()` in the join below? if not the whole thing can be:
```

```
</blockquote></details>

Done.
___
*[`extra_scripts/generate_single_vcf_json_and_copy.py` line 210 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_Rfer4-ll3w4a-F4i:-Nd_pL4x64B26uzxZDTx:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/generate_single_vcf_json_and_copy.py#L210)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

feels like a good time to have a go at using concurrent futures to speed this up :) 

this might be helpful as an example: https://binfx.slack.com/archives/G01HV61U4BX/p1667476200344319
</blockquote></details>

Done.
___
*[`extra_scripts/generate_summary.py` line 100 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3#-Nd_S79L5ynzkaVSD9Jm:-Nd_pLPMEgOzfUFwWjzN:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/4c9702c6e4a8ae8981713e292f48f56b04094385/extra_scripts/generate_summary.py#L100)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

empty print?
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3)* status: 13 of 14 files reviewed, all discussions resolved

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
