### PR TITLE
Updated to perform standard bcftools filtering first

### PR DESCRIPTION
**Pull request by rklocke**
- Updated to take file IDs of genepanels and PanelApp dump as input arguments rather than in config
- Changed code to first perform standard filtering with bcftools (the filter command is now included in config)
- Changed flag of a variant to be either PRIORITISED, NOT_PRIORITISED or NOT_ASSESSED
- Added INFO field with reason if variant is not prioritised
- Removed intermediate VCFs
- Added README with explanation of flags, config and usage

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @rklocke)

___
*[`add_optimised_filtering.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5ZYtQBWVgXAm9qjRj:-Nd5ZYtQBWVgXAm9qjRk:bgn4lql) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/add_optimised_filtering.py#L57)):*
> ```Python
>         required=True,
>         help="DNAnexus file ID of genepanels file with panel IDs included"
>     )
> ```

do you not want to pass the file? does this means it downloads the file every time?



_Code quote:_
```Python
    parser.add_argument(
        '-g',
        '--genepanels',
        type=str,
        required=True,
        help="DNAnexus file ID of genepanels file with panel IDs included"
    )
```
___
*[`add_optimised_filtering.py` line 64 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5Zd7L8TtNYjj-QQEN:-Nd5Zd7L8TtNYjj-QQEO:bnj7hl0) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/add_optimised_filtering.py#L64)):*
> ```Python
>         type=str,
>         required=True,
>         help="DNAnexus file ID of PanelApp JSON dump"
> ```

same as above



_Code quote:_
```Python
     help="DNAnexus file ID of PanelApp JSON dump"
```
___
*[`utils/file_utils.py` line 104 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5b5jo0xswUfltfLBW:-Nd5b5jo0xswUfltfLBX:bfiukjp) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/utils/file_utils.py#L104)):*
> ```Python
>     unescaped_command = json.loads(json.dumps(bcftools_filter_command))
> 
>     return unescaped_command
> ```

can just be one line with the return



_Code quote:_
```Python
    unescaped_command = json.loads(json.dumps(bcftools_filter_command))

    return unescaped_command
```
___
*[`utils/vcf.py` line 237 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5bTs4Ac9HUBZFt-D1:-Nd5bTs4Ac9HUBZFt-D2:brm1796) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/utils/vcf.py#L237)):*
> ```Python
>         for variant in variant_list:
>             if variant.filter.keys()[0] == 'PASS':
>                 if (gene_present) and (gene_moi) and (af_threshold):
> ```

why additional parentheses around these variables? If you're also wanting to check all are not None you can do: `if all([gene_present, gene_moi, af_threshold]):`



_Code quote:_
```Python
if (gene_present) and (gene_moi) and (af_threshold):
```
___
*[`utils/vcf.py` line 269 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5bzG41GYqo0zCHp1W:-Nd5bzG41GYqo0zCHp1X:b-yipxw8) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/utils/vcf.py#L269)):*
> ```Python
>             # Create list of a count of 1 for each variant
>             gt_counts = [genotype.count(1) for genotype in gtypes]
>             count_het_homs = Counter(gt_counts)
> ```

I think an assertion here that the vcf has been decomposed and there's no 0/1/2/3 etc going on would be good



_Code quote:_
```Python
            # Create list of a count of 1 for each variant
            gt_counts = [genotype.count(1) for genotype in gtypes]
            count_het_homs = Counter(gt_counts)
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`add_optimised_filtering.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5ZYtQBWVgXAm9qjRj:-Nd5sPZ7-cpl757HIZRo:b-j4mfgc) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/add_optimised_filtering.py#L57)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you not want to pass the file? does this means it downloads the file every time?
</blockquote></details>

I was looking at dias batch to see how to parse genepanels originally (https://github.com/eastgenomics/dias_batch_running/blob/master/general_functions.py#L771)

Like this, I use dxpy.open_dxfile to read the file directly from DNAnexus rather than downloading it - is this a bad way to do things? Does it make more sense to give the file directly as an input and read from that? 
___
*[`add_optimised_filtering.py` line 64 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5Zd7L8TtNYjj-QQEN:-Nd5sqgm5ZwwkGBLValN:b-6vumu5) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/add_optimised_filtering.py#L64)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Same as above comment
___
*[`utils/file_utils.py` line 104 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5b5jo0xswUfltfLBW:-Nd5tR2e4ffZVMdLdgTH:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/utils/file_utils.py#L104)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can just be one line with the return
</blockquote></details>

Done.
___
*[`utils/vcf.py` line 237 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5bTs4Ac9HUBZFt-D1:-Nd5tvulDwpJUqb0LZI7:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/utils/vcf.py#L237)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why additional parentheses around these variables? If you're also wanting to check all are not None you can do: `if all([gene_present, gene_moi, af_threshold]):`
</blockquote></details>

Done.
___
*[`utils/vcf.py` line 269 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5bzG41GYqo0zCHp1W:-Nd5twrN5XrayGH1RbJA:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/utils/vcf.py#L269)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think an assertion here that the vcf has been decomposed and there's no 0/1/2/3 etc going on would be good
</blockquote></details>

Done.

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`add_optimised_filtering.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5ZYtQBWVgXAm9qjRj:-Nd6CY9lDyUmWycfEDg7:b-jjyla1) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/add_optimised_filtering.py#L57)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you were running it lots locally yes as it would keep reading from DNAnexus, in the context of an app it wouldn't really matter since you'd download it first then read it in as a file, but I'd probs go with taking it in as a file
</blockquote></details>

Changed all inputs to files rather than file IDs and removed function to read files from DNAnexus
___
*[`add_optimised_filtering.py` line 64 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2#-Nd5Zd7L8TtNYjj-QQEN:-Nd6Cde14zhlDsFtuG3y:b-jjyla1) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/397a526af9b531cb426a49e008cce53fb38d767e/add_optimised_filtering.py#L64)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above comment
</blockquote></details>

Changed all inputs to files rather than file IDs and removed function to read files from DNAnexus

**Review by jethror1 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
