### PR TITLE
increment version & add changelog

### PR DESCRIPTION
**Pull request by chrispyatt**
version increased to 1.1.0
changelog added with previous PR details

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17)

### CODE REVIEW

**Review by rklocke — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

___
*[`dxapp.json` line 101 at r1](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17#-NrfZKRM5hUcr1R7ia7G:-NrfZKRM5hUcr1R7ia7H:b8xb7sg) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/68536c12cba539fa29033f9150087b66ed7080f3/dxapp.json#L101)):*
> ```JSON
>     },
>     "details": {
>         "whatsNew": "## Changelog\n* App now warns when no PanelApp ID found in genepanels file (previously caused error)\n* Title conforms to eggd standard\n* Panel string label corrected\n* Pre/post split count bug fixed\n "
> ```

I don't know if we have a standard format for this, but should it be formatted with the version and what's changed in that version, more like eggd_generate_variant_workbook and eggd_vep?

https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/dxapp.json#L7
https://github.com/eastgenomics/eggd_vep/blob/main/dxapp.json#L125



_Code snippet:_
```JSON
"whatsNew": "* v2.0.0 Rewrite of previous app to generate xlsx file from a VEP annotated VCF(s); * v2.0.1 Bug fix to correctly treat CHROM as string values; * v2.0.2 Bug fix for ACMG report template structure;
```

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`dxapp.json` line 101 at r1](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17#-NrfZKRM5hUcr1R7ia7G:-NrgHre-E0q63cDNUh0e:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_optimised_filtering/blob/68536c12cba539fa29033f9150087b66ed7080f3/dxapp.json#L101)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I don't know if we have a standard format for this, but should it be formatted with the version and what's changed in that version, more like eggd_generate_variant_workbook and eggd_vep?

https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/dxapp.json#L7
https://github.com/eastgenomics/eggd_vep/blob/main/dxapp.json#L125
</blockquote></details>

Done.

**Review by rklocke — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

**Review by rklocke — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/17)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)

**Pull request merged**
