### PR TITLE
Di 499 remove bcftools bit replace with tags

### PR DESCRIPTION
**Pull request by chrispyatt**
- didn't actually remove bcftools filter bit (must have been a fever dream)
- changed MOI simplification as in https://cuhbioinformatics.atlassian.net/jira/software/c/projects/DI/issues/DI-520?filter=allissues&jql=project%20%3D%20%22DI%22%20AND%20text%20~%20%22filtering%22%20ORDER%20BY%20created%20DESC
- removed zygosity filtering completely
- removed af filtering
- added MOI tagging instead

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_optimised_filtering/6)

### CODE REVIEW

**Review by rklocke — CHANGES_REQUESTED** [review]
Thanks for making the changes :) just some minor points and I think Matt mentioned about removing the extra_scripts dir from the app as well

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-:-NjMlYvcCPoRlrjdxPTA:b-ieh52f)* status: all files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`resources/add_optimised_filtering.py` line 76 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMcJmD7-GuCNK7Ix4X:-NjMcJmE0xgki25TA_Wv:b-8u1v7b) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/b88a7dc3f4d439f1d867c67c405802bc84290c9c/resources/add_optimised_filtering.py#L76)):*
> ```Python
>     parser.add_argument(
>         '-w',
>         '--whitelist',
> ```

I think this arg can be removed since we decided against using a whitelist in the end
___
*[`resources/utils/panels.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMcnED3s9oLhzRweX8:-NjMcnED3s9oLhzRweX9:bkoj9u5) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/aeb480430f2ba3b2f85f6e4a19bc500b2e558748/resources/utils/panels.py#L154)):*
> ```Python
>         moi = moi_info.get('mode_of_inheritance')
>         xlr = "X-LINKED: hemizygous mutation in males, biallelic mutations in females"
>         xld = "X-LINKED: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males)"
> ```

I've just looped through the whole Panelapp dump and got a set of the unique MOIs (below):
Just checking if we want to include 'Other', 'Other - please specify in evaluation comments', the misspelt 'Other - please specifiy in evaluation comments' and None as 'UNKNOWN'? Or do we want to label them separately? Not sure what's best



_Code snippet:_
```Python
{
    'BIALLELIC, autosomal or pseudoautosomal',
    'BOTH monoallelic and biallelic (but BIALLELIC mutations cause a more SEVERE disease form), autosomal or pseudoautosomal',
    'BOTH monoallelic and biallelic, autosomal or pseudoautosomal',
    'MITOCHONDRIAL',
    'MONOALLELIC, autosomal or pseudoautosomal, NOT imprinted',
    'MONOALLELIC, autosomal or pseudoautosomal, imprinted status unknown',
    'MONOALLELIC, autosomal or pseudoautosomal, maternally imprinted (paternal allele expressed)',
    'MONOALLELIC, autosomal or pseudoautosomal, paternally imprinted (maternal allele expressed)',
    None,
    'Other',
    'Other - please specifiy in evaluation comments',
    'Other - please specify in evaluation comments',
    'Unknown',
    'X-LINKED: hemizygous mutation in males, biallelic mutations in females',
    'X-LINKED: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males)'
}
```
___
*[`resources/utils/vcf.py` line 4 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMmG1S8IIdqsPrkqAE:-NjMmG1S8IIdqsPrkqAF:b-ri39ap) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/b88a7dc3f4d439f1d867c67c405802bc84290c9c/resources/utils/vcf.py#L4)):*
> ```Python
> import subprocess
> 
> from collections import defaultdict, Counter
> ```

I think Counter can be removed from imports since won't be used anymore
___
*[`resources/utils/vcf.py` line 186 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMlLmV-yUXn9buMYCJ:-NjMlLmV-yUXn9buMYCK:bxb61s4) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/aeb480430f2ba3b2f85f6e4a19bc500b2e558748/resources/utils/vcf.py#L186)):*
> ```Python
> 
>     # Add in our new flag to VCF header
>     vcf_contents.header.info.add(
> ```

should the VCF headers Flag and Filter_reason be removed if we're not adding them anymore?

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6)* status: all files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @rklocke)

___
*[`resources/utils/panels.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMcnED3s9oLhzRweX8:-NjRLj_N8QNuxGG9kQd2:b-4ghexy) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/aeb480430f2ba3b2f85f6e4a19bc500b2e558748/resources/utils/panels.py#L154)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I've just looped through the whole Panelapp dump and got a set of the unique MOIs (below):
Just checking if we want to include 'Other', 'Other - please specify in evaluation comments', the misspelt 'Other - please specifiy in evaluation comments' and None as 'UNKNOWN'? Or do we want to label them separately? Not sure what's best
</blockquote></details>

Other* -> OTHER
Unknown -> UNKNOWN

You also have a `None` in there
Let's keep that as a distinct category in case that's ever important
None -> NONE

Anything without a match should also be treated as NONE

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6)* status: 1 of 13 files reviewed, 4 unresolved discussions (waiting on @mattgarner and @rklocke)

___
*[`resources/add_optimised_filtering.py` line 76 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMcJmD7-GuCNK7Ix4X:-NjRaVEYArMFOYLu1Qqk:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/b88a7dc3f4d439f1d867c67c405802bc84290c9c/resources/add_optimised_filtering.py#L76)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I think this arg can be removed since we decided against using a whitelist in the end
</blockquote></details>

Done.
___
*[`resources/utils/panels.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMcnED3s9oLhzRweX8:-NjRdDKyD1jcq_KHUiwN:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/aeb480430f2ba3b2f85f6e4a19bc500b2e558748/resources/utils/panels.py#L154)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Other* -> OTHER
Unknown -> UNKNOWN

You also have a `None` in there
Let's keep that as a distinct category in case that's ever important
None -> NONE

Anything without a match should also be treated as NONE
</blockquote></details>

Done.
___
*[`resources/utils/vcf.py` line 4 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMmG1S8IIdqsPrkqAE:-NjRazmZDrPzqxNpqrbF:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/b88a7dc3f4d439f1d867c67c405802bc84290c9c/resources/utils/vcf.py#L4)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I think Counter can be removed from imports since won't be used anymore
</blockquote></details>

Done.
___
*[`resources/utils/vcf.py` line 186 at r1](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-NjMlLmV-yUXn9buMYCJ:-NjRbLRbCab_7t5lJAqJ:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/aeb480430f2ba3b2f85f6e4a19bc500b2e558748/resources/utils/vcf.py#L186)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

should the VCF headers Flag and Filter_reason be removed if we're not adding them anymore?
</blockquote></details>

Done.

**Review by rklocke — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6#-:-NjRiAH2DIruf4N9YO9W:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)

**Pull request merged**
