### PR TITLE
now an app, with docs

### PR DESCRIPTION
**Pull request by chrispyatt**
moved changes from https://github.com/eastgenomics/eggd_optimised_filtering/pull/1 to this repo

Now runs as app in dnanexus, has zygosity switch, and can use CEN vcfs (though this would be better handled through appropriate bcftools filter string in config)

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @chrispyatt)

___
*[`dxapp.json` line 60 at r2](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3TLNq0hJwg7z8zLc4:-Ng3TLNq0hJwg7z8zLc5:b-kx98n5) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/bfd15b386d5fcd24bce36cefa97fe2b3f3ef9e9e/dxapp.json#L60)):*
> ```JSON
>         "name": "result_files",
>         "label": "sample vcfs, with extra flags added",
>         "class": "array:file"
> ```

why is this an array? my understanding was this would go straight into workbooks, which will want a single file



_Code quote:_
```JSON
class": "array:file"
```
___
*[`README.md` line 2 at r2](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3T_jF8SI_EWKThtEN:-Ng3T_jF8SI_EWKThtEO:b6xdcvj) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/bfd15b386d5fcd24bce36cefa97fe2b3f3ef9e9e/README.md#L2)):*
> ```Markdown
> # eggd_optimised_filtering
> This app takes an annotated VCF (output of eggd_VEP) and adds filtering flags based on gnomad AF thresholds (provided in config) and, if requested, mode of inheritance (also provided in config). The app is adapted from the standalone local tool, the readme for which is partially copied below.
> ```

can this be removed?



_Code quote:_
```Markdown
The app is adapted from the standalone local tool, the readme for which is partially copied below.
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1, 13 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: 14 of 22 files reviewed, 4 unresolved discussions (waiting on @chrispyatt)

___
*[`src/code.sh` line 15 at r3](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3YYJx4oR19q9mrI5d:-Ng3YYJx4oR19q9mrI5e:bxle9mf) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/465c33d9bf9795f609939851cd69c18e0b014e9a/src/code.sh#L15)):*
> ```Shell
>     # install dependencies
>     pip install pysam
>     pip install /pandas*
> ```

don't want to be installing from pypi at runtime, packages can be included in app by doing pip download, can dump them in a dir like: https://github.com/eastgenomics/eggd_generate_variant_workbook/tree/master/resources/home/dnanexus/packages

and to install all: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/src/code.sh#L72



_Code quote:_
```Shell
    pip install pysam
    pip install /pandas*
```
___
*[`src/code.sh` line 28 at r3](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3Yo0m71UpFJVOYp7D:-Ng3Yo0m71UpFJVOYp7E:b-4fpnxn) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/465c33d9bf9795f609939851cd69c18e0b014e9a/src/code.sh#L28)):*
> ```Shell
>     else
>         echo "zygosity option not recognised as true or false, defaulting to false"
>     fi
> ```

since the input is a bool type it only can be true or false, so this isn't needed



_Code quote:_
```Shell
    else
        echo "zygosity option not recognised as true or false, defaulting to false"
    fi
```

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: 14 of 29 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 60 at r2](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3TLNq0hJwg7z8zLc4:-Ng3ZPMPBHvi4DYk2kK9:b-4f0oau) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/bfd15b386d5fcd24bce36cefa97fe2b3f3ef9e9e/dxapp.json#L60)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why is this an array? my understanding was this would go straight into workbooks, which will want a single file
</blockquote></details>

I started off thinking this would produce multiple outputs - have changed now
___
*[`README.md` line 2 at r2](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3T_jF8SI_EWKThtEN:-Ng3Zhx37Rw-zxUgqKjX:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/bfd15b386d5fcd24bce36cefa97fe2b3f3ef9e9e/README.md#L2)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be removed?
</blockquote></details>

Done.
___
*[`src/code.sh` line 15 at r3](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3YYJx4oR19q9mrI5d:-Ng3as0WC80oJdNhQACT:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/465c33d9bf9795f609939851cd69c18e0b014e9a/src/code.sh#L15)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

don't want to be installing from pypi at runtime, packages can be included in app by doing pip download, can dump them in a dir like: https://github.com/eastgenomics/eggd_generate_variant_workbook/tree/master/resources/home/dnanexus/packages

and to install all: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/src/code.sh#L72
</blockquote></details>

Done.
___
*[`src/code.sh` line 28 at r3](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ng3Yo0m71UpFJVOYp7D:-Ng3avit2QWOUjfi0M1h:brpmqb3) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/465c33d9bf9795f609939851cd69c18e0b014e9a/src/code.sh#L28)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since the input is a bool type it only can be true or false, so this isn't needed
</blockquote></details>

removed

**Review by jethror1 — COMMENTED** [review]
> Reviewed 3 of 17 files at r1, 1 of 1 files at r2, 1 of 14 files at r3, 2 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: 21 of 29 files reviewed, 1 unresolved discussion

**Review by jethror1 — APPROVED** [review]
> Reviewed 5 of 10 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 17 files at r1, 14 of 14 files at r3, 6 of 10 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: all files reviewed, 7 unresolved discussions (waiting on @chrispyatt)

___
*[`resources/utils/panels.py` line 52 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgJv3b-AQf1K9SQitO0:-NgJv3b-AQf1K9SQitO1:b-qyuxww) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L52)):*
> ```Python
>     panel_set = genepanels_dict.get(panel_string)
>     try:
>         panel_id = [p_id for p_id in panel_set][0]
> ```

genepanels_dict can contain multiple panels per CI
Therefore, panel_set can contain multiple panels

However, when this is the case this function will only return one of those panels. This seems incorrect.

We should either enforce 1:1 between CI and panel, or return all panels from this function



_Code quote:_
```Python
    panel_set = genepanels_dict.get(panel_string)
    try:
        panel_id = [p_id for p_id in panel_set][0]
```
___
*[`resources/utils/panels.py` line 107 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgJw88G0uN8ovfBCAVg:-NgJw88H4Sq-1PEdfGJ4:b-7u4syl) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L107)):*
> ```Python
>     regions = panel_data.get('regions')
> 
>     if genes:
> ```

Unnecessary `if`

i.e.
Populated list:
```
mylist = [1,2,3]

for thing in mylist:
    print(thing)

print("Done")

1
2
3
Done
```
Empty list:
```
mylist = []

for thing in mylist:
    print(thing)

print("Done")

Done
```



_Code quote:_
```Python
if genes:
```
___
*[`resources/utils/panels.py` line 116 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK-Xn09WlGQ4k4u7q6:-NgK-Xn19wmpFwq0pNms:b-2qbozy) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L116)):*
> ```Python
>                 panel_dict[gene_symbol]['entity_type'] = 'gene'
> 
>     if regions:
> ```

Unnecessary `if`



_Code quote:_
```Python
   if regions:
```
___
*[`resources/utils/panels.py` line 121 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK-sx9AXbXCJGXps71:-NgK-sx9AXbXCJGXps72:b-eu5em8) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L121)):*
> ```Python
>             conf_level = int(region.get('confidence_level'))
>             moi = region.get('mode_of_inheritance')
>             if conf_level >=3:
> ```

Perhaps a comment to explain what the integer versions of confidence levels correspond to (and so why 3 is appropriate)



_Code quote:_
```Python
if conf_level >=3:
```
___
*[`resources/utils/panels.py` line 155 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK0T1E1IEzXkyTdlEM:-NgK0T1F6OvelRXQqyD3:bp1evtd) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L155)):*
> ```Python
>             updated_moi = 'both_monoallelic_and_biallelic'
>         else:
>             updated_moi = 'standard_filtering'
> ```

Shouldn't this be something like "unknown"?

The MOI isn't "standard filtering", that's the decision we'll make downstream



_Code quote:_
```Python
standard_filtering
```
___
*[`resources/utils/panels.py` line 183 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK0rh95Y3pA2T8L3aD:-NgK0rhAEZF9zsZV-VqD:bj6bkd1) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L183)):*
> ```Python
>     # and parse out the gene and region info
>     genepanels_dict = parse_genepanels(genepanels_file)
>     panel_id = get_panel_id_from_genepanels(panel_string, genepanels_dict)
> ```

Could be multiple values of panel_id, see previous comment regarding the function



_Code quote:_
```Python
panel_id = get_panel_id_from_genepanels(panel_string, genepanels_dict)
```
___
*[`resources/utils/vcf.py` line 15 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK2YGO-nhOYkU9EXkV:-NgK2YGO-nhOYkU9EXkW:bhi7ngq) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/vcf.py#L15)):*
> ```Python
>     'SYMBOL', 'Consequence', 'gnomADe_AF', 'gnomADg_AF', 'TWE_AF',
>     'ClinVar_CLNSIG', 'ClinVar_CLNSIGCONF', 'SpliceAI_pred_DS_AG',
>     'SpliceAI_pred_DS_AL', 'SpliceAI_pred_DS_DG', 'SpliceAI_pred_DS_DL'
> ```

If this is a list of VEP CSQ fields we should be extracting those from the vcf so that it's robust to changes.



_Code quote:_
```Python
    'SYMBOL', 'Consequence', 'gnomADe_AF', 'gnomADg_AF', 'TWE_AF',
    'ClinVar_CLNSIG', 'ClinVar_CLNSIGCONF', 'SpliceAI_pred_DS_AG',
    'SpliceAI_pred_DS_AL', 'SpliceAI_pred_DS_DG', 'SpliceAI_pred_DS_DL'
```

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[`resources/utils/panels.py` line 52 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgJv3b-AQf1K9SQitO0:-NgTvd4V7pz0PPY6ibOJ:b-tokbyl) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L52)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

genepanels_dict can contain multiple panels per CI
Therefore, panel_set can contain multiple panels

However, when this is the case this function will only return one of those panels. This seems incorrect.

We should either enforce 1:1 between CI and panel, or return all panels from this function
</blockquote></details>

I've set this to error out if more than 1
___
*[`resources/utils/panels.py` line 107 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgJw88G0uN8ovfBCAVg:-NgU-Siu6UaiEDi5TxkP:be4k98d) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L107)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Unnecessary `if`

i.e.
Populated list:
```
mylist = [1,2,3]

for thing in mylist:
    print(thing)

print("Done")

1
2
3
Done
```
Empty list:
```
mylist = []

for thing in mylist:
    print(thing)

print("Done")

Done
```
</blockquote></details>

I'm not convinced it's totally unnecessary. If the .get('genes') above fails (e.g. because the dict doesn't have a 'genes' attribute for some reason) then there won't even be an empty list. The loop will just raise a TypeError as there's nothing to iterate over. Perhaps we do need something to more explicitly highlight the (potentially) malformed dict though?
___
*[`resources/utils/panels.py` line 116 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK-Xn09WlGQ4k4u7q6:-NgU0ZU24uBt_iWXVJQT:bnj7hl0) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L116)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Unnecessary `if`
</blockquote></details>

same as above
___
*[`resources/utils/panels.py` line 121 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK-sx9AXbXCJGXps71:-NgU22ZU1dFrsnSueOoL:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L121)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps a comment to explain what the integer versions of confidence levels correspond to (and so why 3 is appropriate)
</blockquote></details>

Done.
___
*[`resources/utils/panels.py` line 155 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK0T1E1IEzXkyTdlEM:-NgU2D_M5OWj4OKU5RGd:b-btoh1i) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L155)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Shouldn't this be something like "unknown"?

The MOI isn't "standard filtering", that's the decision we'll make downstream
</blockquote></details>

this just corresponds with whatever is in the config but yes can change to unknown
___
*[`resources/utils/panels.py` line 183 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK0rh95Y3pA2T8L3aD:-NgU4cli2Pedx6-xewCX:bslwpbv) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L183)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could be multiple values of panel_id, see previous comment regarding the function
</blockquote></details>

not any more
___
*[`resources/utils/vcf.py` line 15 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgK2YGO-nhOYkU9EXkV:-NgUIkaO6ANFjVZrOU31:b-uruxb2) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/vcf.py#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

If this is a list of VEP CSQ fields we should be extracting those from the vcf so that it's robust to changes.
</blockquote></details>

This list can now be provided via the config (I think Becky was in the process of doing this already but it wasn't in the code). The list is passed through to the relevant places.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r4, 4 of 4 files at r6, all commit messages.
> Dismissed @mattgarner from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

___
*[`resources/utils/panels.py` line 107 at r5](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-NgJw88G0uN8ovfBCAVg:-NgXu3ml-AyzSsRSwugJ:b-wbakme) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/3b75470560d9cf079756d3927100bfef096242ba/resources/utils/panels.py#L107)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

I'm not convinced it's totally unnecessary. If the .get('genes') above fails (e.g. because the dict doesn't have a 'genes' attribute for some reason) then there won't even be an empty list. The loop will just raise a TypeError as there's nothing to iterate over. Perhaps we do need something to more explicitly highlight the (potentially) malformed dict though?
</blockquote></details>

You're correct. I was (incorrectly) thinking `.get` would return `[]` rather than `None` if the key was not found.
___
*[`src/code.sh` line 15 at r6](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ngc-51I0nz2M3Fqt1LV:-Ngc-51I0nz2M3Fqt1LW:b-be3e3c) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/6d788829ac02135ea1e9e5702e82c655fbb2deec/src/code.sh#L15)):*
> ```Shell
>     # install dependencies
>     sudo -H python3 -m pip install --no-index --no-deps packages/*
>     export BCFTOOLS_PLUGINS=/usr/local/libexec/bcftools
> ```

Do you think this would be better placed outside/above main() ?



_Code quote:_
```Shell
    # install dependencies
    sudo -H python3 -m pip install --no-index --no-deps packages/*
    export BCFTOOLS_PLUGINS=/usr/local/libexec/bcftools
```

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4)* status: 29 of 32 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[`src/code.sh` line 15 at r6](https://reviewable.io/reviews/eastgenomics/optimised_filtering/4#-Ngc-51I0nz2M3Fqt1LV:-NgdC-ZYCgtQ3VOS4Kv3:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/6d788829ac02135ea1e9e5702e82c655fbb2deec/src/code.sh#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do you think this would be better placed outside/above main() ?
</blockquote></details>

Done.

**Pull request merged**
